# fly.toml app configuration file generated for malortron on 2023-09-18T09:00:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "malortron"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[processes]
  app = "python3 nullctf.py"

[checks]
  [checks.malortron]
    port = 8080
    type = "tcp"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
